"""add prior_month_total and difference to items

Revision ID: 124e1f58ae91
Revises: ea1fa6dea662
Create Date: 2026-01-13 18:43:19.036979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124e1f58ae91'
down_revision = 'ea1fa6dea662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prior_month_total', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('difference', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('difference')
        batch_op.drop_column('prior_month_total')

    # ### end Alembic commands ###
