"""create item_monthly_totals

Revision ID: a6339db6493a
Revises: 124e1f58ae91
Create Date: 2026-01-14 16:04:40.989974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6339db6493a'
down_revision = '124e1f58ae91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_monthly_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('month_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_monthly_totals')
    # ### end Alembic commands ###
